### ISSUE TITLE
/node/show/<hostname> ends in error since upgrade to 0.17.1

### ISSUE THREAD

**Issue by davromaniak** [ytti/oxidized-web#365]
Hi.

Earlier today, I updated oxidized-web to 0.17.1 (and oxidized to 0.34.2).

Since this, any query to `/node/show/<hostname>` ends in error with the message : 

```
NoMethodError at /node/show/<hostname>
undefined method `transform_keys' for nil:NilClass data[:vars] = data[:vars].transform_keys(&:to_s) ^^^^^^^^^^^^^^^
file: webapp.rb location: filter_node_vars line: 335
```

Here's the full log : 
```
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: 2025-08-04 15:40:55 - NoMethodError - undefined method `transform_keys' for nil:NilClass
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]:        data[:vars] = data[:vars].transform_keys(&:to_s)
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]:                                 ^^^^^^^^^^^^^^^:
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/oxidized-web-0.17.1/lib/oxidized/web/webapp.rb:335:in `filter_node_vars'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/oxidized-web-0.17.1/lib/oxidized/web/webapp.rb:130:in `block in <class:WebApp>'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1807:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1807:in `block in compile!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1074:in `block (3 levels) in route!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1092:in `route_eval'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1074:in `block (2 levels) in route!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1123:in `block in process_route'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1121:in `catch'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1121:in `process_route'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1072:in `block in route!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1069:in `each'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1069:in `route!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1193:in `block in dispatch!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1164:in `catch'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1164:in `invoke'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1188:in `dispatch!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1004:in `block in call!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1164:in `catch'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1164:in `invoke'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1004:in `call!'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:993:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-protection-4.1.1/lib/rack/protection/base.rb:53:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-protection-4.1.1/lib/rack/protection/xss_header.rb:20:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-protection-4.1.1/lib/rack/protection/path_traversal.rb:18:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-protection-4.1.1/lib/rack/protection/json_csrf.rb:28:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-protection-4.1.1/lib/rack/protection/base.rb:53:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-protection-4.1.1/lib/rack/protection/frame_options.rb:33:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/middleware/logger.rb:17:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-3.2.0/lib/rack/head.rb:15:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/show_exceptions.rb:23:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:227:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:2138:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1677:in `block in call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1898:in `synchronize'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/sinatra-4.1.1/lib/sinatra/base.rb:1677:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-3.2.0/lib/rack/urlmap.rb:76:in `block in call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-3.2.0/lib/rack/urlmap.rb:60:in `each'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-3.2.0/lib/rack/urlmap.rb:60:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/rack-3.2.0/lib/rack/builder.rb:283:in `call'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/puma-6.6.1/lib/puma/request.rb:99:in `block in handle_request'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/puma-6.6.1/lib/puma/thread_pool.rb:390:in `with_force_shutdown'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/puma-6.6.1/lib/puma/request.rb:98:in `handle_request'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/puma-6.6.1/lib/puma/server.rb:472:in `process_client'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/puma-6.6.1/lib/puma/server.rb:254:in `block in run'
Aug  4 15:40:55 monwmsnetmon01 oxidized[383263]: #011/usr/local/share/gems/gems/puma-6.6.1/lib/puma/thread_pool.rb:167:in `block in spawn_thread'
```

I checked and the host called do have a backed up configuration.

Oxidized is using a local Git repo, here's the output part of Oxidized config : 

```
output:
  default: git
  git:
    single_repo: true
    user: Oxidized
    repo: "/opt/oxidized/devices"
    type_as_directory: true
```

Don't hesitate to ask any question or any info I may have missed.

Thanks.

**Comment by ytti** [comment]
Try changing this https://github.com/ytti/oxidized-web/blob/2ab1c49357e71e18a8b5ddf398c8bf788cd4c61b/lib/oxidized/web/webapp.rb#L335

```ruby
data[:vars] = data[:vars].transform_keys(&:to_s)
```

into

```ruby
data[:vars] = data[:vars]&.transform_keys(&:to_s)
```

Not 100% sure why vars would be nil, instead of empty hash. So this fix may not be appropriate one, even if it works. Appropriate fix may be to guarantee that vars hash exists.

**Comment by davromaniak** [comment]
I confirm it also works on my side.

Thanks a lot for the quick answer and fix.
